FORMAT: 1A
HOST: https://iot-room-climate-regulator.herokuapp.com/webapi

# iot-room-climate-regulator

IOT Room Climate Regulator. Receives tempreture regulation task and reserves 
it on the same level. Also provides logging of process.

## Ping [/ping]

### Ping service [GET]

Returns `200` if service is alive.

+ Response 200 (application/json)


## Floor Temperature [/houses/{house_id}/floors/{floor_id}]

+ Parameters
    + house_id (required, string, `12`) ... House identifier
    + floor_id (required, string, `3`) ... Floor identifier

### Add new regulation task [PUT]

Returns `200` status code if regulation task is accepted otherwise `404`

`temperature` is a floating point number indicating desired temperature.
`period` is an integer indicating time period in msecs while regulation task is active. 

+ Request (application/json)

        {
            "temperature": 22.5,
            "period": 50000
        }
        
+ Response 200 (application/json)
+ Response 404 (application/json)